import java.util.Arrays;
import java.util.Comparator;

public class ClientsList {
  public String[] dataCleanup(String[] names) {
    return Arrays.stream(names)
        .map(
            name -> {
              String[] parts = name.split(" ");

              return parts[0].endsWith(",")
                  ? new Name(parts[1], parts[0].substring(0, parts[0].length() - 1))
                  : new Name(parts[0], parts[1]);
            })
        .sorted(Comparator.comparing((Name name) -> name.last).thenComparing(name -> name.first))
        .map(n -> String.format("%s %s", n.first, n.last))
        .toArray(String[]::new);
  }

  class Name {
    String first;
    String last;

    Name(String first, String last) {
      this.first = first;
      this.last = last;
    }
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(
      int testNum, String[] p0, boolean hasAnswer, String[] p1) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}");
    System.out.println("]");
    ClientsList obj;
    String[] answer;
    obj = new ClientsList();
    long startTime = System.currentTimeMillis();
    answer = obj.dataCleanup(p0);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.print("\t" + "{");
      for (int i = 0; p1.length > i; ++i) {
        if (i > 0) {
          System.out.print(",");
        }
        System.out.print("\"" + p1[i] + "\"");
      }
      System.out.println("}");
    }
    System.out.println("Your answer:");
    System.out.print("\t" + "{");
    for (int i = 0; answer.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + answer[i] + "\"");
    }
    System.out.println("}");
    if (hasAnswer) {
      if (answer.length != p1.length) {
        res = false;
      } else {
        for (int i = 0; answer.length > i; ++i) {
          if (!answer[i].equals(p1[i])) {
            res = false;
          }
        }
      }
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    String[] p1;

    // ----- test 0 -----
    p0 = new String[] {"Joe Smith", "Brown, Sam", "Miller, Judi"};
    p1 = new String[] {"Sam Brown", "Judi Miller", "Joe Smith"};
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new String[] {"Campbell, Phil", "John Campbell", "Young, Warren"};
    p1 = new String[] {"John Campbell", "Phil Campbell", "Warren Young"};
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new String[] {"Kelly, Anthony", "Kelly Anthony", "Thompson, Jack"};
    p1 = new String[] {"Kelly Anthony", "Anthony Kelly", "Jack Thompson"};
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 =
        new String[] {
          "Trevor Alvarez",
          "Jackson, Walter",
          "Mandi Stuart",
          "Martin, Michael",
          "Peters, Tammy",
          "Richard Belmont",
          "Carl Thomas",
          "Ashton, Roger",
          "Jamie Martin"
        };
    p1 =
        new String[] {
          "Trevor Alvarez",
          "Roger Ashton",
          "Richard Belmont",
          "Walter Jackson",
          "Jamie Martin",
          "Michael Martin",
          "Tammy Peters",
          "Mandi Stuart",
          "Carl Thomas"
        };
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = new String[] {"Banks, Cody", "Cody Banks", "Tod Wilson"};
    p1 = new String[] {"Cody Banks", "Cody Banks", "Tod Wilson"};
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = new String[] {"Mill, Steve", "Miller, Jane"};
    p1 = new String[] {"Steve Mill", "Jane Miller"};
    all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
