import java.util.Arrays;
import java.util.stream.IntStream;

public class Hangman {
  public String guessWord(String feedback, String[] words) {
    String[] candidates =
        Arrays.stream(words).filter(word -> isMatch(feedback, word)).toArray(String[]::new);

    return (candidates.length == 1) ? candidates[0] : "";
  }

  boolean isMatch(String feedback, String word) {
    return feedback.length() == word.length()
        && IntStream.range(0, 26)
            .allMatch(
                i -> {
                  char letter = (char) (i + 'A');

                  int[] feedbackIndices =
                      IntStream.range(0, feedback.length())
                          .filter(j -> feedback.charAt(j) == letter)
                          .toArray();
                  int[] wordIndices =
                      IntStream.range(0, word.length())
                          .filter(j -> word.charAt(j) == letter)
                          .toArray();

                  return feedbackIndices.length == 0 || Arrays.equals(feedbackIndices, wordIndices);
                });
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(
      int testNum, String p0, String[] p1, boolean hasAnswer, String p2) {
    System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "{");
    for (int i = 0; p1.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p1[i] + "\"");
    }
    System.out.print("}");
    System.out.println("]");
    Hangman obj;
    String answer;
    obj = new Hangman();
    long startTime = System.currentTimeMillis();
    answer = obj.guessWord(p0, p1);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + "\"" + p2 + "\"");
    }
    System.out.println("Your answer:");
    System.out.println("\t" + "\"" + answer + "\"");
    if (hasAnswer) {
      res = answer.equals(p2);
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String p0;
    String[] p1;
    String p2;

    // ----- test 0 -----
    p0 = "N-N-A";
    p1 = new String[] {"NINJA", "NINJAS", "FLIPS", "OUT", "FRISBEE"};
    p2 = "NINJA";
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = "B--B--";
    p1 = new String[] {"BRINGS", "BARBED", "BUBBLE"};
    p2 = "BARBED";
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = "---------";
    p1 = new String[] {"MONKEY", "FORCE", "IS", "GAINING", "STRENGTH"};
    p2 = "";
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = "-AAA--";
    p1 = new String[] {"CAAABB", "BAAACC"};
    p2 = "";
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = "---H-O-H-B-OPHOB--";
    p1 =
        new String[] {
          "ROSACEA",
          "GYROVAGUE",
          "SHACONIAN",
          "ALTITONANT",
          "BRACHIATION",
          "CERCOPITHECAN",
          "SCOLECOPHAGOUS",
          "RESISTENTIALISM",
          "SLUBBERDEGULLION",
          "AICHMORHABDOPHOBIA",
          "SPECTOCLOACAPHOBIA",
          "ULTRACREPIDARIANISM",
          "HIPPOPOTOMONSTROSESQUIPEDALIAN",
          "CHARGOGGAGOGGMANCHAUGGAGOGGCHAUBUNAGUNGAMAUGG"
        };
    p2 = "AICHMORHABDOPHOBIA";
    all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
