import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.IntStream;

public class PlugStuffIn {
  public int[] plug(int[] gadgets) {
    int[] result = new int[gadgets.length];
    Arrays.fill(result, -1);

    int[] cordIndices = IntStream.range(0, gadgets.length).filter(i -> gadgets[i] >= 2).toArray();
    List<Integer> sockets = new ArrayList<>();
    if (cordIndices.length == 0) {
      sockets.add(gadgets.length);
    } else {
      for (int i = 0; i < cordIndices.length; ++i) {
        if (i == 0) {
          result[cordIndices[i]] = gadgets.length;
        } else {
          result[cordIndices[i]] = cordIndices[i - 1];
        }

        for (int j = 0;
            j < gadgets[cordIndices[i]] - ((i == cordIndices.length - 1) ? 0 : 1);
            ++j) {
          sockets.add(cordIndices[i]);
        }
      }
    }

    int[] deviceIndices = IntStream.range(0, gadgets.length).filter(i -> gadgets[i] == 0).toArray();
    if (deviceIndices.length > sockets.size()) {
      return new int[0];
    }

    for (int i = 0; i < deviceIndices.length; ++i) {
      result[deviceIndices[i]] = sockets.get(i);
    }

    return result;
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, int[] p0, boolean hasAnswer, int[] p1) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print(p0[i]);
    }
    System.out.print("}");
    System.out.println("]");
    PlugStuffIn obj;
    int[] answer;
    obj = new PlugStuffIn();
    long startTime = System.currentTimeMillis();
    answer = obj.plug(p0);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.print("\t" + "{");
      for (int i = 0; p1.length > i; ++i) {
        if (i > 0) {
          System.out.print(",");
        }
        System.out.print(p1[i]);
      }
      System.out.println("}");
    }
    System.out.println("Your answer:");
    System.out.print("\t" + "{");
    for (int i = 0; answer.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print(answer[i]);
    }
    System.out.println("}");
    if (hasAnswer) {
      if (answer.length != p1.length) {
        res = false;
      } else {
        for (int i = 0; answer.length > i; ++i) {
          if (answer[i] != p1[i]) {
            res = false;
          }
        }
      }
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    int[] p0;
    int[] p1;

    // ----- test 0 -----
    p0 = new int[] {0};
    p1 = new int[] {1};
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = new int[] {1, 1, 0, 1, 1, 1};
    p1 = new int[] {-1, -1, 4, -1, 6, -1};
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = new int[] {1, 1, 0, 1, 1, 1, 0};
    p1 = new int[] {};
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new int[] {0, 0, 2, 0, 2};
    p1 = new int[] {2, 4, 5, 4, 2};
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = new int[] {0, 3, 3};
    p1 = new int[] {3, 2, 1};
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = new int[] {10, 20, 30, 40};
    p1 = new int[] {-1, 1, -1, -1};
    all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
