import java.util.stream.IntStream;

public class StreetParking {
  public int freeParks(String street) {
    return (int)
        IntStream.range(0, street.length())
            .filter(
                i ->
                    street.charAt(i) != 'D'
                        && street.charAt(i) != 'B'
                        && (i + 1 >= street.length() || street.charAt(i + 1) != 'B')
                        && (i + 2 >= street.length() || street.charAt(i + 2) != 'B')
                        && street.charAt(i) != 'S'
                        && (i + 1 >= street.length() || street.charAt(i + 1) != 'S')
                        && (i - 1 < 0 || street.charAt(i - 1) != 'S'))
            .count();
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, int p1) {
    System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
    System.out.println("]");
    StreetParking obj;
    int answer;
    obj = new StreetParking();
    long startTime = System.currentTimeMillis();
    answer = obj.freeParks(p0);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + p1);
    }
    System.out.println("Your answer:");
    System.out.println("\t" + answer);
    if (hasAnswer) {
      res = answer == p1;
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String p0;
    int p1;

    // ----- test 0 -----
    p0 = "---B--S-D--S--";
    p1 = 4;
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = "DDBDDBDDBDD";
    p1 = 0;
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = "--S--S--S--S--";
    p1 = 2;
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = "SSD-B---BD-DDSB-----S-S--------S-B----BSB-S--B-S-D";
    p1 = 14;
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
