import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class TextEditor {
  public String[] twoColumn(String[] text, int width) {
    String[] words =
        Arrays.stream(text)
            .flatMap(line -> Arrays.stream(line.split(" ")))
            .filter(word -> !word.isEmpty())
            .toArray(String[]::new);

    List<String> sections = new ArrayList<>();
    String current = "";
    for (String word : words) {
      String added = String.format("%s%s%s", current, current.isEmpty() ? "" : " ", word);
      if (added.length() <= width) {
        current = added;
      } else {
        sections.add(current);
        current = word;
      }
    }
    if (!current.isEmpty()) {
      sections.add(current);
    }

    String[] result = new String[sections.size()];
    int index = 0;
    for (int i = 0; i < result.length; i += 2) {
      result[i] = sections.get(index);
      ++index;
    }
    for (int i = 1; i < result.length; i += 2) {
      result[i] = sections.get(index);
      ++index;
    }

    return result;
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(
      int testNum, String[] p0, int p1, boolean hasAnswer, String[] p2) {
    System.out.print("Test " + testNum + ": [" + "{");
    for (int i = 0; p0.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + p0[i] + "\"");
    }
    System.out.print("}" + "," + p1);
    System.out.println("]");
    TextEditor obj;
    String[] answer;
    obj = new TextEditor();
    long startTime = System.currentTimeMillis();
    answer = obj.twoColumn(p0, p1);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.print("\t" + "{");
      for (int i = 0; p2.length > i; ++i) {
        if (i > 0) {
          System.out.print(",");
        }
        System.out.print("\"" + p2[i] + "\"");
      }
      System.out.println("}");
    }
    System.out.println("Your answer:");
    System.out.print("\t" + "{");
    for (int i = 0; answer.length > i; ++i) {
      if (i > 0) {
        System.out.print(",");
      }
      System.out.print("\"" + answer[i] + "\"");
    }
    System.out.println("}");
    if (hasAnswer) {
      if (answer.length != p2.length) {
        res = false;
      } else {
        for (int i = 0; answer.length > i; ++i) {
          if (!answer[i].equals(p2[i])) {
            res = false;
          }
        }
      }
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String[] p0;
    int p1;
    String[] p2;

    // ----- test 0 -----
    p0 = new String[] {"The quick brown fox jumps over the lazy dog. "};
    p1 = 7;
    p2 = new String[] {"The", "over", "quick", "the", "brown", "lazy", "fox", "dog.", "jumps"};
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 =
        new String[] {
          "Such a preposterous use of !punctuation! !!!",
          "Who would write ... something like this ???"
        };
    p1 = 17;
    p2 =
        new String[] {
          "Such a",
          "write ...",
          "preposterous use",
          "something like",
          "of !punctuation!",
          "this ???",
          "!!! Who would"
        };
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 =
        new String[] {
          " Forsaking monastic tradition,    twelve jovial",
          "  friars gave up their vocation for a questionable",
          "     existence on the flying trapeze.    "
        };
    p1 = 25;
    p2 =
        new String[] {
          "Forsaking monastic",
          "vocation for a",
          "tradition, twelve jovial",
          "questionable existence on",
          "friars gave up their",
          "the flying trapeze."
        };
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = new String[] {" ", " ", " ", " ", " ", " "};
    p1 = 7;
    p2 = new String[] {};
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 =
        new String[] {
          " I WONDER by my troth, what thou,",
          "and I Did, till we lovd? were we",
          "not weand till then? But suckd on",
          "countrey pleasures, childishly? Or",
          "snorted we in the seaven sleepers",
          "den? Twas so; But this, all",
          "pleasures fancies bee. If ever any",
          "beauty I did see, Which I desird,",
          "and got, twas but a dreame of",
          "thee. And now good morrow to our",
          "waking soules, Which watch not one",
          "another out of feare; For love, all",
          "love of other sights controules,",
          "And makes one little roome, an",
          "every where. Let seadiscoverers to",
          "new worlds have gone, Let Maps to",
          "other, worlds on worlds have",
          "showne, Let us possesse one world,",
          "each hath one, and is one. My face",
          "in thine eye, thine in mine",
          "appeares, And true plaine hearts",
          "doe in the faces rest, Where can we",
          "finde two better hemispheares",
          "Without sharpe North, without",
          "declining West? What ever dyes, was",
          "not mixt equally; If our two loves",
          "be one, or, thou and I Love so",
          "alike, that none doe slacken, none",
          "can die.",
          "John D" + "onne"
        };
    p1 = 45;
    p2 =
        new String[] {
          "I WONDER by my troth, what thou, and I Did,",
          "seadiscoverers to new worlds have gone, Let",
          "till we lovd? were we not weand till then?",
          "Maps to other, worlds on worlds have showne,",
          "But suckd on countrey pleasures, childishly?",
          "Let us possesse one world, each hath one, and",
          "Or snorted we in the seaven sleepers den?",
          "is one. My face in thine eye, thine in mine",
          "Twas so; But this, all pleasures fancies bee.",
          "appeares, And true plaine hearts doe in the",
          "If ever any beauty I did see, Which I desird,",
          "faces rest, Where can we finde two better",
          "and got, twas but a dreame of thee. And now",
          "hemispheares Without sharpe North, without",
          "good morrow to our waking soules, Which watch",
          "declining West? What ever dyes, was not mixt",
          "not one another out of feare; For love, all",
          "equally; If our two loves be one, or, thou",
          "love of other sights controules, And makes",
          "and I Love so alike, that none doe slacken,",
          "one little roome, an every where. Let",
          "none can die. John Donne"
        };
    all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
