public class UnLinker {
  public String clean(String text) {
    String result = text;
    for (int i = 1; ; ++i) {
      String next =
          result.replaceFirst(
              "(http://|http://www\\.|www\\.)[a-zA-Z0-9.]+\\.(com|org|edu|info|tv)",
              String.format("OMIT%d", i));

      if (next.equals(result)) {
        return result;
      }

      result = next;
    }
  }

  // BEGIN KAWIGIEDIT TESTING
  // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
  private static boolean KawigiEdit_RunTest(int testNum, String p0, boolean hasAnswer, String p1) {
    System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"");
    System.out.println("]");
    UnLinker obj;
    String answer;
    obj = new UnLinker();
    long startTime = System.currentTimeMillis();
    answer = obj.clean(p0);
    long endTime = System.currentTimeMillis();
    boolean res;
    res = true;
    System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
    if (hasAnswer) {
      System.out.println("Desired answer:");
      System.out.println("\t" + "\"" + p1 + "\"");
    }
    System.out.println("Your answer:");
    System.out.println("\t" + "\"" + answer + "\"");
    if (hasAnswer) {
      res = answer.equals(p1);
    }
    if (!res) {
      System.out.println("DOESN'T MATCH!!!!");
    } else if ((endTime - startTime) / 1000.0 >= 2) {
      System.out.println("FAIL the timeout");
      res = false;
    } else if (hasAnswer) {
      System.out.println("Match :-)");
    } else {
      System.out.println("OK, but is it right?");
    }
    System.out.println("");
    return res;
  }

  public static void main(String[] args) {
    boolean all_right;
    all_right = true;

    String p0;
    String p1;

    // ----- test 0 -----
    p0 = "espihttp://www.tv.org.superwww.cali.comaladocious";
    p1 = "espiOMIT1aladocious";
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------

    // ----- test 1 -----
    p0 = "check www.foo.com 4 www.foo.com www.scoopz.com";
    p1 = "check OMIT1 4 OMIT2 OMIT3";
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------

    // ----- test 2 -----
    p0 = "check www.foo.com 4 www.foo.comwww.scoopz.com";
    p1 = "check OMIT1 4 OMIT2";
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------

    // ----- test 3 -----
    p0 = "check www.foo.com 4 www.foo.comhttp://scoopz.com";
    p1 = "check OMIT1 4 OMIT2OMIT3";
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------

    // ----- test 4 -----
    p0 = "http://411.com goodz 4 www.733t.com, 2http://..com";
    p1 = "OMIT1 goodz 4 OMIT2, 2OMIT3";
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------

    // ----- test 5 -----
    p0 = "http.//say.org,www.jeeves.x.info,www.comhttp://.tv";
    p1 = "http.//say.org,OMIT1,www.comhttp://.tv";
    all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
    // ------------------

    // ----- test 6 -----
    p0 = "http://www.www.com/www";
    p1 = "OMIT1/www";
    all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
    // ------------------

    if (all_right) {
      System.out.println("You're a stud (at least on the example cases)!");
    } else {
      System.out.println("Some of the test cases had errors.");
    }
  }
  // END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
