public class SlayingDeer {
	public int getTime(int A, int B, int C) {
		if (A * 45 <= B * 30) {
			return -1;
		}

		int time = 0;

		while (A * 45 < B * 30 + C) {
			time += 45;
			C -= A * 45 - B * 30;
		}

		if (A * 30 >= B * 30 + C) {
			return time + divideToCeil(C, A - B);
		}

		time += 30;
		C -= A * 30 - B * 30;

		return time + divideToCeil(C, A);
	}

	int divideToCeil(int x, int y) {
		return (x + y - 1) / y;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2);
		System.out.println("]");
		SlayingDeer obj;
		int answer;
		obj = new SlayingDeer();
		long startTime = System.currentTimeMillis();
		answer = obj.getTime(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		int p0;
		int p1;
		int p2;
		int p3;

		// ----- test 0 -----
		p0 = 5;
		p1 = 4;
		p2 = 20;
		p3 = 20;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = 5;
		p1 = 4;
		p2 = 47;
		p3 = 34;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = 10;
		p1 = 17;
		p2 = 1;
		p3 = -1;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = 133;
		p1 = 198;
		p2 = 7515;
		p3 = 7515;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 4 -----
		p0 = 1;
		p1 = 1000;
		p2 = 15819;
		p3 = -1;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
