import java.util.Arrays;

public class StockHistory {
	public int maximumEarnings(int initialInvestment, int monthlyContribution, String[] stockPrices) {
		int[] lastPrices = Arrays.stream(stockPrices[stockPrices.length - 1].split(" ")).mapToInt(Integer::parseInt)
				.toArray();
		double profit = 0;
		double rate = 0;
		for (int i = stockPrices.length - 2; i >= 0; --i) {
			String[] parts = stockPrices[i].split(" ");
			for (int j = 0; j < parts.length; ++j) {
				int price = Integer.parseInt(parts[j]);
				rate = Math.max(rate, (double) (lastPrices[j] - price) / price);
			}

			int amount = (i == 0) ? initialInvestment : monthlyContribution;
			profit += amount * rate;
		}

		return (int) Math.round(profit);
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, String[] p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p2[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		StockHistory obj;
		int answer;
		obj = new StockHistory();
		long startTime = System.currentTimeMillis();
		answer = obj.maximumEarnings(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		int p0;
		int p1;
		String[] p2;
		int p3;

		// ----- test 0 -----
		p0 = 1000;
		p1 = 0;
		p2 = new String[] { "10 20 30", "15 24 32" };
		p3 = 500;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = 1000;
		p1 = 0;
		p2 = new String[] { "10", "9" };
		p3 = 0;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = 100;
		p1 = 20;
		p2 = new String[] { "40 50 60", "37 48 55", "100 48 50", "105 48 47", "110 50 52", "110 50 52", "110 51 54",
				"109 49 53" };
		p3 = 239;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
